// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDucBjkj-6iytYByAceY8ZJKgr9zPp_WZQ',
    appId: '1:285068335558:web:35fb95f9420455b0d2bac7',
    messagingSenderId: '285068335558',
    projectId: 'ecommerappdeshimarket',
    authDomain: 'ecommerappdeshimarket.firebaseapp.com',
    storageBucket: 'ecommerappdeshimarket.appspot.com',
    measurementId: 'G-SB0SF1Q4PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDRGs2yZdhdmIgUV1dhyMcNkPrZWHWtA',
    appId: '1:285068335558:android:6029ae65b9ad9f1cd2bac7',
    messagingSenderId: '285068335558',
    projectId: 'ecommerappdeshimarket',
    storageBucket: 'ecommerappdeshimarket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqsKgGZUbxhpKYDUuAUuLS8tqtVGRmc-c',
    appId: '1:285068335558:ios:2c77e7affb9070d2d2bac7',
    messagingSenderId: '285068335558',
    projectId: 'ecommerappdeshimarket',
    storageBucket: 'ecommerappdeshimarket.appspot.com',
    iosBundleId: 'com.example.eCommerceFruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqsKgGZUbxhpKYDUuAUuLS8tqtVGRmc-c',
    appId: '1:285068335558:ios:2c77e7affb9070d2d2bac7',
    messagingSenderId: '285068335558',
    projectId: 'ecommerappdeshimarket',
    storageBucket: 'ecommerappdeshimarket.appspot.com',
    iosBundleId: 'com.example.eCommerceFruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDucBjkj-6iytYByAceY8ZJKgr9zPp_WZQ',
    appId: '1:285068335558:web:d9c25df971370a2ed2bac7',
    messagingSenderId: '285068335558',
    projectId: 'ecommerappdeshimarket',
    authDomain: 'ecommerappdeshimarket.firebaseapp.com',
    storageBucket: 'ecommerappdeshimarket.appspot.com',
    measurementId: 'G-D9JF00HY1X',
  );
}
